#!/usr/bin/env node
"use strict"

/*
 * webhook-sample.js — sample Peach Payments webhook generator for LOCAL testing.
 *
 * PURPOSE
 *   Generates correctly-signed sample Peach Payments webhook payloads so a developer
 *   can test their webhook receiver locally without initiating or waiting for real
 *   transactions. Complements scripts/verify-webhook.js (which verifies payloads).
 *
 * FOR LOCAL TESTING ONLY
 *   Samples generated by this script are synthetic test payloads designed to test
 *   local receivers (e.g. localhost, ngrok, test endpoints). Never use sample
 *   payloads in production and never transmit real production secrets.
 *
 * SCHEMES
 *   Scheme A — classic Checkout body signature (application/x-www-form-urlencoded):
 *     The signature is a field INSIDE the body (signature=<hex>).
 *     Canonical string = all other parameters (including empty values) sorted
 *     alphabetically by key, concatenated as key + value with NO separators;
 *     HMAC-SHA256 hex using the Checkout secret token.
 *   Scheme B — header signing (Dashboard -> Webhook security):
 *     Canonical string = `${timestamp}.${webhookId}.${configuredUrl}.${rawBody}`;
 *     HMAC-SHA256 hex using the webhook shared secret; transmitted in headers:
 *     x-webhook-signature-algorithm, x-webhook-signature, x-webhook-timestamp,
 *     and x-webhook-id. Checkout bodies are form-urlencoded; Payment Links bodies are JSON.
 *
 * TAMPERING (--tamper)
 *   Mutates a field (e.g. amount) AFTER computing the signature so the payload carries
 *   an invalid signature. Used to verify that your webhook receiver properly rejects
 *   unauthenticated or tampered payloads (fails closed).
 *
 * RUNTIME: Node >= 18, zero external dependencies (Node builtin `crypto` only). No network.
 * Deterministic given a fixed --timestamp.
 *
 * EXIT CODES: 0 = success / selftest passed; 1 = selftest failed; 2 = usage/input error.
 */

const crypto = require("crypto")

// Reuse exported verifier functions for selftest and cross-scheme verification
let verifyModule
try {
  verifyModule = require("./verify-webhook")
} catch (_) {
  verifyModule = null
}

const PROG = "webhook-sample.js"

/* ────────────────────────────────────────────────────────────────────────────
 * Canonical builders & helpers
 * ──────────────────────────────────────────────────────────────────────────── */

/** Timing-safe string compare with length check. */
function timingSafeEqualStrings(a, b) {
  const ab = Buffer.from(String(a || ""))
  const bb = Buffer.from(String(b || ""))
  if (ab.length !== bb.length) return false
  return crypto.timingSafeEqual(ab, bb)
}

/** HMAC-SHA256 hex digest — secret is used verbatim as UTF-8 bytes. */
function hmacSha256Hex(secret, message) {
  return crypto.createHmac("sha256", secret).update(message, "utf8").digest("hex")
}

/**
 * Format amount as 2-decimal place string (e.g. "10.00").
 * Avoids any * 100 multiplication to preserve major-unit convention.
 */
function formatAmount(amount) {
  if (typeof amount === "number") {
    if (!Number.isFinite(amount)) {
      throw new Error("webhook-sample: amount must be a finite number or decimal string")
    }
    return amount.toFixed(2)
  }
  const str = String(amount == null ? "" : amount).trim()
  if (!str) return "10.00"
  if (/^\d+$/.test(str)) return `${str}.00`
  if (/^\d+\.\d$/.test(str)) return `${str}0`
  if (/^\d+\.\d{2}$/.test(str)) return str
  const num = Number(str)
  if (!Number.isNaN(num) && Number.isFinite(num)) {
    return num.toFixed(2)
  }
  return str
}

/** Default human explanation for common Peach result codes. */
function defaultResultDescription(code) {
  switch (code) {
    case "000.000.000":
      return "Transaction succeeded"
    case "000.100.110":
      return "Request successfully processed in Merchant Advice System"
    case "000.200.000":
      return "Transaction pending"
    case "000.200.100":
      return "Successfully created checkout"
    case "100.396.101":
      return "Cancelled by user"
    case "100.396.104":
      return "Uncertain transaction status"
    case "800.100.150":
      return "Transaction declined"
    default:
      return "Transaction processed"
  }
}

/**
 * Scheme A canonical string builder:
 * Drops `signature`, sorts remaining keys alphabetically,
 * concatenates key + value with NO separators (including empty values).
 */
function classicMessage(params) {
  const entries = []
  for (const [k, v] of Object.entries(params || {})) {
    if (k !== "signature") {
      entries.push([k, v == null ? "" : String(v)])
    }
  }
  entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
  return entries.map(([k, v]) => `${k}${v}`).join("")
}

/**
 * Generate a ready-to-run curl command string.
 * Command string only — never executes network calls.
 */
function buildCurlCommand(opts) {
  const { url, contentType, headers = {}, rawBody = "" } = opts
  const lines = [`curl -X POST '${url}'`]
  if (contentType) {
    lines.push(`  -H 'Content-Type: ${contentType}'`)
  }
  for (const [k, v] of Object.entries(headers)) {
    lines.push(`  -H '${k}: ${v}'`)
  }
  const escapedBody = rawBody.replace(/'/g, "'\\''")
  lines.push(`  --data '${escapedBody}'`)
  return lines.join(" \\\n")
}

/* ────────────────────────────────────────────────────────────────────────────
 * Sample Generators
 * ──────────────────────────────────────────────────────────────────────────── */

/**
 * Generate a Scheme A (classic Checkout body signature) sample.
 *
 * @param {object} opts
 *   secret        {string} Checkout secret token (required)
 *   code?         {string} Result code (default: "000.000.000")
 *   description?  {string} Result description
 *   amount?       {string|number} Amount in major units (default: "10.00")
 *   currency?     {string} Currency (default: "ZAR")
 *   checkoutId?   {string} Checkout ID (default deterministic test ID)
 *   id?           {string} Transaction ID (default deterministic 32-hex)
 *   timestamp?    {string|number} Fixed epoch seconds or ISO string (default: now)
 *   tamper?       {boolean} When true, mutate amount after signing
 *   curl?         {string} URL for ready-to-run curl command
 */
function generateClassicSample(opts = {}) {
  const { secret, code, description, amount, currency, checkoutId, id, timestamp, tamper, curl } = opts

  if (secret == null || secret === "") {
    throw new Error("webhook-sample: --secret is required (Checkout secret token for Scheme A)")
  }

  // Deterministic timestamp resolution
  const nowSec = timestamp != null ? String(timestamp) : Math.floor(Date.now() / 1000).toString()
  const isNumericTs = /^\d+$/.test(nowSec)
  const epochSec = isNumericTs ? nowSec : Math.floor(new Date(nowSec).getTime() / 1000).toString()
  const isoTimestamp = isNumericTs ? new Date(Number(epochSec) * 1000).toISOString() : nowSec

  const txId = id || crypto.createHash("sha256").update(`tx:${epochSec}`).digest("hex").slice(0, 32)
  const chkId = checkoutId || "CHECKOUT00000000000000000000TEST"
  const resultCode = code || "000.000.000"
  const resultDesc = description || defaultResultDescription(resultCode)
  const formattedAmount = formatAmount(amount)

  const fields = {
    amount: formattedAmount,
    checkoutId: chkId,
    currency: currency || "ZAR",
    id: txId,
    merchantTransactionId: `ORD-${epochSec}`,
    paymentBrand: opts.paymentBrand || "VISA",
    paymentType: opts.paymentType || "DB",
    "recon.authCode": opts.reconAuthCode || "006887",
    "recon.rrn": opts.reconRrn || "000000123456",
    "result.code": resultCode,
    "result.description": resultDesc,
    timestamp: isoTimestamp,
  }

  // Build sorted URLSearchParams for deterministic output
  const params = new URLSearchParams()
  const keys = Object.keys(fields).sort()
  for (const k of keys) {
    params.set(k, fields[k])
  }

  // Canonical string and HMAC-SHA256 hex signature
  const canonical = classicMessage(fields)
  const signature = hmacSha256Hex(secret, canonical)
  params.set("signature", signature)

  // Tamper: mutate amount AFTER signing if requested
  if (tamper) {
    const tamperedAmount = fields.amount === "99999.00" ? "1.00" : "99999.00"
    params.set("amount", tamperedAmount)
    fields.amount = tamperedAmount
  }

  const rawBody = params.toString()
  const curlCommand = curl
    ? buildCurlCommand({
        url: curl,
        contentType: "application/x-www-form-urlencoded",
        rawBody,
      })
    : undefined

  return {
    scheme: "classic",
    fields,
    canonical,
    signature,
    rawBody,
    contentType: "application/x-www-form-urlencoded",
    tampered: Boolean(tamper),
    curlCommand,
  }
}

/**
 * Generate a Scheme B (header signing) sample.
 *
 * @param {object} opts
 *   secret        {string} Webhook shared secret (required)
 *   url?          {string} Configured webhook URL in Dashboard (required unless curl provided)
 *   code?         {string} Result code (default: "000.000.000")
 *   description?  {string} Result description
 *   amount?       {string|number} Amount in major units (default: "10.00")
 *   currency?     {string} Currency (default: "ZAR")
 *   checkoutId?   {string} Checkout ID (default deterministic test ID)
 *   id?           {string} Transaction ID (default deterministic 32-hex)
 *   webhookId?    {string} Custom webhook ID (default deterministic)
 *   timestamp?    {string|number} Fixed epoch seconds or ISO string (default: now)
 *   format?       {string} "json" (default) or "form"
 *   tamper?       {boolean} When true, mutate payload after signing
 *   curl?         {string} URL for ready-to-run curl command
 */
function generateHeaderSample(opts = {}) {
  const { secret, url, code, description, amount, currency, checkoutId, id, webhookId, timestamp, format, tamper, curl } = opts

  if (secret == null || secret === "") {
    throw new Error("webhook-sample: --secret is required (webhook shared secret for Scheme B)")
  }

  const targetUrl = url || curl
  if (targetUrl == null || targetUrl === "") {
    throw new Error("webhook-sample: --url <configuredUrl> is required for Scheme B header signing")
  }

  const nowSec = timestamp != null ? String(timestamp) : Math.floor(Date.now() / 1000).toString()
  const isNumericTs = /^\d+$/.test(nowSec)
  const epochSec = isNumericTs ? nowSec : Math.floor(new Date(nowSec).getTime() / 1000).toString()
  const isoTimestamp = isNumericTs ? new Date(Number(epochSec) * 1000).toISOString() : nowSec

  const txId = id || crypto.createHash("sha256").update(`tx:${epochSec}`).digest("hex").slice(0, 32)
  const chkId = checkoutId || "CHECKOUT00000000000000000000TEST"
  const whId = webhookId || `wh_${crypto.createHash("sha256").update(`wh:${epochSec}`).digest("hex").slice(0, 16)}`
  const resultCode = code || "000.000.000"
  const resultDesc = description || defaultResultDescription(resultCode)
  const formattedAmount = formatAmount(amount)

  const fields = {
    amount: formattedAmount,
    checkoutId: chkId,
    currency: currency || "ZAR",
    id: txId,
    merchantTransactionId: `ORD-${epochSec}`,
    paymentBrand: opts.paymentBrand || "VISA",
    paymentType: opts.paymentType || "DB",
    "recon.authCode": opts.reconAuthCode || "006887",
    "recon.rrn": opts.reconRrn || "000000123456",
    "result.code": resultCode,
    "result.description": resultDesc,
    timestamp: isoTimestamp,
  }

  const isForm = String(format || "json").toLowerCase() === "form"
  let rawBody
  let contentType

  if (isForm) {
    const params = new URLSearchParams()
    for (const k of Object.keys(fields).sort()) {
      params.set(k, fields[k])
    }
    rawBody = params.toString()
    contentType = "application/x-www-form-urlencoded"
  } else {
    const sortedObj = {}
    for (const k of Object.keys(fields).sort()) {
      sortedObj[k] = fields[k]
    }
    rawBody = JSON.stringify(sortedObj)
    contentType = "application/json"
  }

  // Canonical message: ${timestamp}.${webhookId}.${configuredUrl}.${rawBody}
  const canonical = `${epochSec}.${whId}.${targetUrl}.${rawBody}`
  const signature = hmacSha256Hex(secret, canonical)

  const headers = {
    "x-webhook-signature-algorithm": "HMAC-SHA256",
    "x-webhook-signature": signature,
    "x-webhook-timestamp": epochSec,
    "x-webhook-id": whId,
  }

  // Tamper: mutate payload body AFTER signing
  if (tamper) {
    if (isForm) {
      const p = new URLSearchParams(rawBody)
      const tamperedAmount = p.get("amount") === "99999.00" ? "1.00" : "99999.00"
      p.set("amount", tamperedAmount)
      rawBody = p.toString()
      fields.amount = tamperedAmount
    } else {
      const parsed = JSON.parse(rawBody)
      parsed.amount = parsed.amount === "99999.00" ? "1.00" : "99999.00"
      rawBody = JSON.stringify(parsed)
      fields.amount = parsed.amount
    }
  }

  const curlCommand = curl
    ? buildCurlCommand({
        url: curl,
        contentType,
        headers,
        rawBody,
      })
    : undefined

  return {
    scheme: "header",
    fields,
    headers,
    canonical,
    signature,
    rawBody,
    contentType,
    tampered: Boolean(tamper),
    curlCommand,
  }
}

/** Dispatch generator by scheme ("classic" | "header"). */
function generateSample(opts = {}) {
  const scheme = (opts.scheme || "classic").toLowerCase()
  if (scheme === "classic") {
    return generateClassicSample(opts)
  }
  if (scheme === "header") {
    return generateHeaderSample(opts)
  }
  throw new Error(`webhook-sample: unknown scheme '${opts.scheme}' (expected 'classic' or 'header')`)
}

/* ────────────────────────────────────────────────────────────────────────────
 * CLI Argument Parsing
 * ──────────────────────────────────────────────────────────────────────────── */

function norm(k) {
  return k.toLowerCase().replace(/[^a-z0-9]/g, "")
}

const BOOL_FLAGS = new Set(["tamper", "help", "bodyonly", "headersonly"])

function parseArgs(argv) {
  const out = { command: undefined, help: false, flags: {}, error: undefined }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === "--help" || a === "-h") {
      out.help = true
      continue
    }
    if (a.startsWith("--")) {
      let key = a.slice(2)
      let value
      const eq = key.indexOf("=")
      if (eq !== -1) {
        value = key.slice(eq + 1)
        key = key.slice(0, eq)
      } else if (BOOL_FLAGS.has(norm(key))) {
        value = true
      } else if (i + 1 < argv.length && !argv[i + 1].startsWith("--")) {
        value = argv[++i]
      } else {
        out.error = `flag --${key} requires a value`
        return out
      }
      out.flags[norm(key)] = value
      continue
    }
    if (out.command === undefined) {
      out.command = a
    } else {
      out.error = `unexpected extra argument '${a}'`
      return out
    }
  }
  return out
}

function resolveFlags(flags) {
  const get = (...names) => {
    for (const n of names) {
      const v = flags[norm(n)]
      if (v !== undefined) return v
    }
    return undefined
  }
  return {
    scheme: get("scheme"),
    secret: get("secret"),
    url: get("url", "webhookurl"),
    curl: get("curl"),
    code: get("code"),
    amount: get("amount"),
    currency: get("currency"),
    checkoutId: get("checkout-id", "checkoutid", "chk"),
    id: get("id", "transaction-id", "transactionid"),
    webhookId: get("webhook-id", "webhookid"),
    timestamp: get("timestamp", "ts"),
    format: get("format"),
    tamper: Boolean(get("tamper")),
    bodyOnly: Boolean(get("body-only", "bodyonly")),
    headersOnly: Boolean(get("headers-only", "headersonly")),
  }
}

function printHelp() {
  console.log(`${PROG} — generate correctly-signed sample Peach Payments webhooks (Node >= 18, zero deps)

LOCAL TESTING ONLY:
  Generate sample webhook payloads to test your receiver locally without waiting
  for a real transaction. Never use in production.

SCHEMES
  classic    Scheme A — classic Checkout body signature (application/x-www-form-urlencoded).
             The signature is a field inside the body (signature=<hex>).
             Canonical string is all parameters sorted alphabetically, concatenated key+value
             with no separators, HMAC-SHA256 hex using Checkout secret token.
  header     Scheme B — header signing (Dashboard -> Webhook security).
             Canonical string = \`\${timestamp}.\${webhookId}.\${configuredUrl}.\${rawBody}\`;
             HMAC-SHA256 hex; sent in x-webhook-signature / timestamp / id headers.

USAGE
  ${PROG} --scheme classic --secret <token> [options]
  ${PROG} --scheme header --secret <secret> --url <configuredUrl> [options]
  ${PROG} selftest
  ${PROG} --help

OPTIONS
  --scheme <classic|header>  Webhook scheme (default: classic)
  --secret <token>           Checkout secret token (classic) or webhook shared secret (header).
                             Required. Never printed or logged.
  --url <configuredUrl>      Configured webhook URL in Dashboard (required for header scheme)
  --code <code>              Result code (default: 000.000.000)
  --amount <amount>          Amount in major units (default: 10.00)
  --currency <currency>      Currency (default: ZAR)
  --checkout-id <id>         Checkout ID (default: CHECKOUT00000000000000000000TEST)
  --timestamp <ts>           Unix epoch seconds (e.g. 1718700000) or ISO string for deterministic output
  --format <json|form>       Body format for header scheme (default: json)
  --webhook-id <id>          Custom webhook ID for header scheme
  --tamper                   Mutate payload after signing to produce an INVALID signature (tests receiver rejection)
  --curl <url>               Also print a ready-to-run curl command (command only; no network executed)
  --body-only                Print raw body only
  --headers-only             Print header lines only (Scheme B)

EXIT CODES
  0  Success / selftest passed
  1  Selftest failed
  2  Usage or argument error

EXAMPLES
  # Generate classic Checkout webhook (prints raw urlencoded body ready to POST):
  node scripts/${PROG} --scheme classic --secret "$SECRET"

  # Pipe directly into verify-webhook.js to verify:
  node scripts/${PROG} --scheme classic --secret "$SECRET" | node scripts/verify-webhook.js verify --secret "$SECRET"

  # Test receiver rejection with a tampered sample:
  node scripts/${PROG} --scheme classic --secret "$SECRET" --tamper

  # Scheme B with header lines and JSON body:
  node scripts/${PROG} --scheme header --secret "$SECRET" --url "http://localhost:3000/api/webhook"

  # Print ready-to-run curl command to test local server:
  node scripts/${PROG} --scheme classic --secret "$SECRET" --curl "http://localhost:3000/api/webhook"`)
}

function usageError(msg) {
  console.error(`${PROG}: error: ${msg}`)
  console.error(`run '${PROG} --help' for usage`)
  process.exitCode = 2
}

/* ────────────────────────────────────────────────────────────────────────────
 * Selftest
 * ──────────────────────────────────────────────────────────────────────────── */

function runSelftest() {
  if (!verifyModule) {
    throw new Error("verify-webhook.js could not be required for selftest")
  }

  const { verifyPeachWebhook, verifyClassicRaw, verifyHeaderScheme } = verifyModule
  const SECRET = "test_checkout_secret_token_12345"
  const URL = "https://example.com/api/webhook"
  const FIXED_TS = "1718700000"

  const tests = []
  const t = (name, fn) => tests.push({ name, fn })
  const check = (cond, msg) => {
    if (!cond) throw new Error(msg || "assertion failed")
  }

  // 1. Classic sample verifies TRUE
  t("generateClassicSample: verifies TRUE with verify-webhook.js", () => {
    const sample = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS })
    const r1 = verifyClassicRaw(SECRET, sample.rawBody)
    check(r1.valid === true, `verifyClassicRaw failed: ${JSON.stringify(r1)}`)
    const r2 = verifyPeachWebhook({ secretToken: SECRET, rawBody: sample.rawBody })
    check(r2.valid === true, `verifyPeachWebhook failed: ${JSON.stringify(r2)}`)
  })

  // 2. Classic tampered sample verifies FALSE
  t("generateClassicSample: --tamper variant verifies FALSE (signature_mismatch)", () => {
    const sample = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS, tamper: true })
    check(sample.tampered === true, "tampered flag must be true")
    const r = verifyPeachWebhook({ secretToken: SECRET, rawBody: sample.rawBody })
    check(r.valid === false && r.reason === "signature_mismatch", `expected signature_mismatch, got ${JSON.stringify(r)}`)
  })

  // 3. Header sample (JSON) verifies TRUE
  t("generateHeaderSample (JSON): verifies TRUE with verify-webhook.js", () => {
    const sample = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, format: "json" })
    const r = verifyPeachWebhook({
      secretToken: SECRET,
      headers: sample.headers,
      url: URL,
      rawBody: sample.rawBody,
    })
    check(r.valid === true && r.scheme === "ts.id.url.payload", `expected ts.id.url.payload, got ${JSON.stringify(r)}`)
  })

  // 4. Header sample (JSON) tampered verifies FALSE
  t("generateHeaderSample (JSON): --tamper variant verifies FALSE (signature_mismatch)", () => {
    const sample = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, format: "json", tamper: true })
    check(sample.tampered === true, "tampered flag must be true")
    const r = verifyPeachWebhook({
      secretToken: SECRET,
      headers: sample.headers,
      url: URL,
      rawBody: sample.rawBody,
    })
    check(r.valid === false && r.reason === "signature_mismatch", `expected signature_mismatch, got ${JSON.stringify(r)}`)
  })

  // 5. Header sample (form) verifies TRUE
  t("generateHeaderSample (form): verifies TRUE with verify-webhook.js", () => {
    const sample = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, format: "form" })
    const r = verifyPeachWebhook({
      secretToken: SECRET,
      headers: sample.headers,
      url: URL,
      rawBody: sample.rawBody,
    })
    check(r.valid === true, `form-urlencoded header sample failed: ${JSON.stringify(r)}`)
  })

  // 6. Header sample (form) tampered verifies FALSE
  t("generateHeaderSample (form): --tamper variant verifies FALSE (signature_mismatch)", () => {
    const sample = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, format: "form", tamper: true })
    check(sample.tampered === true, "tampered flag must be true")
    const r = verifyPeachWebhook({
      secretToken: SECRET,
      headers: sample.headers,
      url: URL,
      rawBody: sample.rawBody,
    })
    check(r.valid === false && r.reason === "signature_mismatch", `expected signature_mismatch, got ${JSON.stringify(r)}`)
  })

  // 7. Determinism: classic scheme
  t("determinism: classic scheme with fixed timestamp produces byte-identical output", () => {
    const s1 = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS, code: "000.000.000", amount: "25.00" })
    const s2 = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS, code: "000.000.000", amount: "25.00" })
    check(s1.rawBody === s2.rawBody, "rawBody diverged on identical inputs")
    check(s1.signature === s2.signature, "signature diverged on identical inputs")
    check(s1.canonical === s2.canonical, "canonical string diverged on identical inputs")
  })

  // 8. Determinism: header scheme
  t("determinism: header scheme with fixed timestamp produces byte-identical output", () => {
    const h1 = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, code: "000.100.110", amount: "50.00" })
    const h2 = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, code: "000.100.110", amount: "50.00" })
    check(h1.rawBody === h2.rawBody, "header rawBody diverged on identical inputs")
    check(h1.headers["x-webhook-signature"] === h2.headers["x-webhook-signature"], "header signature diverged")
    check(h1.headers["x-webhook-id"] === h2.headers["x-webhook-id"], "header webhookId diverged")
  })

  // 9. Custom parameters: classic
  t("custom parameters: code, amount, checkoutId, and currency are preserved and verified", () => {
    const sample = generateClassicSample({
      secret: SECRET,
      code: "000.200.000",
      amount: "199.99",
      checkoutId: "chk_custom_12345",
      currency: "KES",
      timestamp: FIXED_TS,
    })
    check(sample.fields["result.code"] === "000.200.000", "code mismatch")
    check(sample.fields.amount === "199.99", "amount mismatch")
    check(sample.fields.checkoutId === "chk_custom_12345", "checkoutId mismatch")
    check(sample.fields.currency === "KES", "currency mismatch")
    const r = verifyPeachWebhook({ secretToken: SECRET, rawBody: sample.rawBody })
    check(r.valid === true, "custom classic sample failed verification")
  })

  // 10. Amount canonicalisation
  t("amount canonicalisation: number and decimal strings are formatted to 2dp", () => {
    check(formatAmount(10) === "10.00", "10 -> 10.00")
    check(formatAmount("10") === "10.00", "'10' -> 10.00")
    check(formatAmount(10.5) === "10.50", "10.5 -> 10.50")
    check(formatAmount("10.5") === "10.50", "'10.5' -> 10.50")
    check(formatAmount("10.00") === "10.00", "'10.00' -> 10.00")
  })

  // 11. Wrong secret rejection
  t("rejection on wrong secret: classic and header samples fail when checked against different secret", () => {
    const sClassic = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS })
    const rClassic = verifyPeachWebhook({ secretToken: "wrong_secret", rawBody: sClassic.rawBody })
    check(rClassic.valid === false, "classic must fail with wrong secret")

    const sHeader = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS })
    const rHeader = verifyPeachWebhook({
      secretToken: "wrong_secret",
      headers: sHeader.headers,
      url: URL,
      rawBody: sHeader.rawBody,
    })
    check(rHeader.valid === false, "header must fail with wrong secret")
  })

  // 12. Curl command generation
  t("curl command generation: --curl builds valid command string containing headers and body", () => {
    const classic = generateClassicSample({ secret: SECRET, timestamp: FIXED_TS, curl: "http://localhost:3000/hook" })
    check(classic.curlCommand.includes("curl -X POST 'http://localhost:3000/hook'"), "curl url missing in classic")
    check(classic.curlCommand.includes("application/x-www-form-urlencoded"), "curl content-type missing in classic")

    const header = generateHeaderSample({ secret: SECRET, url: URL, timestamp: FIXED_TS, curl: "http://localhost:3000/hook" })
    check(header.curlCommand.includes("curl -X POST 'http://localhost:3000/hook'"), "curl url missing in header")
    check(header.curlCommand.includes("application/json"), "curl content-type missing in header")
    check(header.curlCommand.includes("x-webhook-signature:"), "curl header signature missing")
  })

  // 13. Usage / input validation errors
  t("usage validation: missing secret or missing url throws actionable errors", () => {
    let err1 = false
    try {
      generateClassicSample({ secret: "" })
    } catch (e) {
      err1 = true
    }
    check(err1, "missing secret must throw")

    let err2 = false
    try {
      generateHeaderSample({ secret: SECRET, url: "" })
    } catch (e) {
      err2 = true
    }
    check(err2, "missing url for header scheme must throw")
  })

  let failed = 0
  for (const { name, fn } of tests) {
    try {
      fn()
      console.log(`PASS  ${name}`)
    } catch (e) {
      failed++
      console.log(`FAIL  ${name}`)
      console.log(`      ${e.message}`)
    }
  }

  console.log(`\n${tests.length - failed}/${tests.length} passed`)
  process.exitCode = failed ? 1 : 0
  return failed === 0
}

/* ────────────────────────────────────────────────────────────────────────────
 * CLI Execution
 * ──────────────────────────────────────────────────────────────────────────── */

async function main(argv) {
  const parsed = parseArgs(argv)
  if (parsed.error) return usageError(parsed.error)

  if (parsed.help) {
    printHelp()
    process.exitCode = 0
    return
  }

  const cmd = (parsed.command || "").toLowerCase()
  if (cmd === "selftest") {
    runSelftest()
    return
  }
  if (cmd === "help") {
    printHelp()
    process.exitCode = 0
    return
  }
  if (cmd && !cmd.startsWith("-")) {
    return usageError(`unknown command '${parsed.command}' (expected 'selftest' or options)`)
  }

  const flags = resolveFlags(parsed.flags)
  const scheme = (flags.scheme || "classic").toLowerCase()

  if (!["classic", "header"].includes(scheme)) {
    return usageError(`--scheme must be 'classic' or 'header' (got '${flags.scheme}')`)
  }

  if (flags.secret === undefined || flags.secret === "") {
    return usageError("missing required --secret <checkout secret token / webhook shared secret>")
  }

  let sample
  try {
    sample = generateSample({
      scheme,
      secret: flags.secret,
      url: flags.url,
      curl: flags.curl,
      code: flags.code,
      amount: flags.amount,
      currency: flags.currency,
      checkoutId: flags.checkoutId,
      id: flags.id,
      webhookId: flags.webhookId,
      timestamp: flags.timestamp,
      format: flags.format,
      tamper: flags.tamper,
    })
  } catch (err) {
    return usageError(err.message)
  }

  // Print tamper warning notice to stderr so machine pipes are preserved
  if (sample.tampered) {
    console.error("# NOTE: This sample has been TAMPERED with (--tamper). A valid receiver MUST reject it.")
  }

  // Handle specialized print flags
  if (flags.bodyOnly) {
    console.log(sample.rawBody)
    process.exitCode = 0
    return
  }

  if (flags.headersOnly) {
    if (scheme === "classic") {
      console.log("# Scheme A carries signature in body (signature= field), no custom signing headers.")
    } else {
      for (const [k, v] of Object.entries(sample.headers)) {
        console.log(`${k}: ${v}`)
      }
    }
    process.exitCode = 0
    return
  }

  // Standard output formatting
  if (scheme === "classic") {
    if (flags.curl) {
      console.log("# Sample Peach Webhook (Scheme A — classic body signature):")
      if (sample.tampered) {
        console.log("# NOTE: This sample has been TAMPERED with (--tamper). A valid receiver MUST reject it.")
      }
      console.log(sample.rawBody)
      console.log("")
      console.log("# Ready-to-run curl command (local testing only):")
      console.log(sample.curlCommand)
    } else {
      // Direct raw form-urlencoded output for immediate pipe/POST usage
      console.log(sample.rawBody)
    }
  } else {
    // Scheme B: Header signing
    console.log("# Headers:")
    for (const [k, v] of Object.entries(sample.headers)) {
      console.log(`${k}: ${v}`)
    }
    console.log("")
    console.log(`# Body (${sample.contentType}):`)
    if (sample.tampered) {
      console.log("# NOTE: This sample has been TAMPERED with (--tamper). A valid receiver MUST reject it.")
    }
    console.log(sample.rawBody)

    if (flags.curl) {
      console.log("")
      console.log("# Ready-to-run curl command (local testing only):")
      console.log(sample.curlCommand)
    }
  }

  process.exitCode = 0
}

if (require.main === module) {
  main(process.argv.slice(2)).catch((e) => {
    console.error(`${PROG}: error: ${e && e.message ? e.message : e}`)
    process.exitCode = 2
  })
}

module.exports = {
  generateSample,
  generateClassicSample,
  generateHeaderSample,
  classicMessage,
  formatAmount,
  defaultResultDescription,
  buildCurlCommand,
  timingSafeEqualStrings,
  runSelftest,
  parseArgs,
}
